[google_credentials]
type = "service_account"
project_id = "terasaka-demo"
private_key_id = "51aa7380d913d5b54eb4e4dde5dc5f2804f289d0"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCU8nLthFrmdbj5
6e7rYE5jawXVCCBttHy9TpmZ8DisY+PTzrQpdxCoqOUs/CM2mhNZ7qpf2VdJBaB7
REEgPynQz01Os2+K4h+/syjU+XrbqwonCfZDyNIPY9j+PLy4XKWB5v/Ct/qyyJ3m
17b11wHFO7/EsHo20JMTNdMRJiQu/eMiLf+e7qzCRkyyJbTheu8gfeESnNJhkhKg
RRT7pEk4joJToZpZY3nAYwLShlalvk/+MGJPaMTFFQeZ2+XDeD8H/NymFITzOMPW
sdRbubTG+P84WQPuq/XUHGC5wlw/ZUwPpEiZwbRoJmSr7b9EHjg2ZhhXq67HgHFt
+UyySp8XAgMBAAECggEAAKU8UkMskasY7hxRaLu2G0Avekjaux75G2jnyX78/+I+
7oAKz9MwQ0rYE2XUUTxBsTYTju7GLg7ULzSQg69CYyFC2IB2j0eDk7UXDDU4jxMi
rCCi7JBGOMLaAeAJgVMFdJanrRRXBcdQx9tPc6lG3K/xmMya+vnUaVTmYUClD38Q
d6GUugK0EG67TS/elpun5e0ODVojz2V55OG+EzNoPnn12tdSQixgjrBHmLlf7T9F
TIU2ViMyi8Kr1P2HoRFPLTNevM10BK8FXCPMI1KvO5DQq0EVroW1ObK5E5xI/ZYp
Fy89SvJ/0x/j6bElfMvx/kY/tm2keiiiYYYyLwOwIQKBgQDFYQwO2mNCLqDkTFo9
Nn/W2VMItOHZziY3W3KvrNkfTsQ1OPW0ITddkTiRcE/UmiXO0X1EmAe+IQt3IkwG
oL80yGyJ1b9EvRjIkjNp1tIyP6uUX464o9+eT/XIcPWbjEm0MuZW+PLDa8tf3v77
oCIztcWVGqw4TN6WrVnMfQwygwKBgQDBLw+W/r+hcKzb2ewe5kDyy7d8Dju55TEA
zinfDI5eTMLKlDPsFViFlvmCgcnAlVVO4lLLX3YLL49XFPt7cTNpVoH06WaKAOgO
DV23B8TBZs8COI/CoeIz/snz7W525loU2NbAyKhi5vqIyF9HTChgP4HgX9Uui6iU
TLkA63Gs3QKBgQCum4OHQDq+uXErhT/vFt9QuUBzW1DQ1UWJgySZtFb/EzcPvive
BeRsqaNZRfnZIeSAaWJf4/41fBYgdf67fkin8QXTiXuC26WpCWziHGAmg5zNzRr8
zDtuWV4cy5D64cfx2XVbSy+3IQzw6ty2zJp1FECN/uKLi7T9pqzh8V1w8QKBgDU4
iNv5bMPGLekXnWRZ3NTG6NLFfRDWomxtX72yUNqL3TJAKBnHO676C903cmSa/3iP
A25B61xjiuLbxfiZFCfWDFFzp6snWsbcSdAt1LfPYgJjoL9nJ9FZRTvtUnxxM6oA
nxFXdoRgy+64/P7AbXMuq9IrtKhxE01f4avuMVAFAoGAEuWI+tdSFuF0OM+k8UbI
LW4t/8F+oRfF9OEF7MxqXpUSMQNndLQbNa5ML6xQoZ+KcnW3eTXtFY42bmlDhjd5
dzjJ2OmOrzp3tpYzwpclanVD3YIZgzZPsFoSZ3UCNeK+X0wWij+vAI4FHzFyJLpm
O2OBoC8NA4+aKvn5pM/YDD8=
-----END PRIVATE KEY-----"""
client_email = "terasaka-demo@terasaka-demo.iam.gserviceaccount.com"
client_id = "100290504332764846323"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri =  "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/terasaka-demo%40terasaka-demo.iam.gserviceaccount.com"
universe_domain = "googleapis.com"