[google_credentials]
type = "service_account"
project_id = "terasaka-demo"
private_key_id = "7b096a1814c20e0b940dc0b50a1205f72dfbc048"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDJgaNN81mh0TJp
1PKfgNBXfHAaVD+oKrkEzkZ0i7K1jugfHN8K7JPf3eNv5ugmB4cUI8hcKxJpEm34
fJly8+yf1+EqM3IogrVKvLJV+3JwesAgNN0P28ChXNbHrTgmRr3q6d6jt0JUhf/X
X93a0BK8YkyWv5cR7o1ZQrmlCdi5T1xLhLlRXcwODs37s/ijQxAwetkBAYZSAzjN
sd1v4zfE06CpdGJuqXNIpvGJw7os623TqUR8xMiNOxJFheW9zOBNnsoGW3b6dDFu
M6isKWv2rLr8s+eyJffGdnN3jXuKkpZG0a4jBkb27XuDmcXL0JcbwBHHGHfeniVt
cabFB2BJAgMBAAECggEAD4nSO41xetWIfUn1FBjhJ+/h7pvSxU9XEVBtNSk9FHxC
uLx3lA5yaDPCaSN9gQo5T7OjLH1LSAQqa/wCsq8tztUdKS2KpuZOX8cdet0fAd6r
UEh3R/TmfaLssnzQXL49gJ78YrQ71ov3MqbTMx9ypGlxlbnMJs82Ad0v9tKjrkVV
5hUCAZwGvWMUZ31sUcBaoUCGkMTWF8t2JE8HJPvWhotpN3zOewT8ZQVbVSG/YqMx
GEIjEjlxYxNBhTawGQUnssZLB8iF7Kn2GNoV+G29SiqoesQdfC31rtCUKTmWla+Z
cc3sa4P82GgBbDanhPgS5Ulgv/XhYHcUJ+tgumA8wQKBgQDw+aNv06lIA5w6MKoa
7xUvHA6fQRnWmO6aPmYRRnxxhy24UIZoJ0IRwSN0xBdQPGcm7n+OURixSjwW8gls
qEkg3NR6RY8vu70bDc1yWcylDWATNzIQoaVmpeZNBbxswtXD2lZhX3f0qamfGxp2
jNztdCnACfYqKBbv36Y5GE8WiQKBgQDWEgNS637dhIH5kLQTbdikhUjLS/guov9v
d4xpmihov0TmQbCNOuzLzOnKKdywVTSm3ehD8/y0kz98+8a4TkTdjaCF9u9CRwj1
8/wR79MRftP4lEH7HfrNW1ZB0mMpTDvJURbhbOfvFVdfWdwlKbWSHnbxI2jdKv8b
hDTGNBOLwQKBgFXx0za5GPEUSI4AeUrt5nJM4XIvN9Xv6Xmds62JpCyhd876+VUA
W3IVnl2w6le1k1yxR1Es30+sGE5euLnGM37DBA0v7eeqX8HcZF/aY0CiypdP4k1I
OcOoe8EQwKlRvAgEQTatZA0gzdxvQDrz9n/CJHnXk7JpZfTboV9PqjVxAoGAZi+r
DoYDxVJfiPYeP7gL1l0ZZpIZIooETP1QNYi1CWtkRFXPJVufdZmXcD2Tb0j9HTqI
iQeK9dfkUpENRyV1khztJ4W8qHKoQF/7T8SfiJZ2MQ70gB7LfgO/pSP82dXeJDdl
KK6H+ITDdGy8vbCvT9TjCjDQ+eJwbH4rgwGQ4wECgYEAkdDj/h12O6QVDhU2Y0VW
u+ILGLHKe/oZMm6hvu07bBCu72rqjgn+dBTH67f8y9+2wMwKEhgtLxljelSXWY4r
r62lTAcStW+yRa1x0r/0EMhMot/7u9Jc+iyx3yiprCrlaloBL190XxgX7MzIwljB
2x9l33HI1W9aTN8wC8sMX90=
-----END PRIVATE KEY-----"""
client_email = "terasaka-demo@terasaka-demo.iam.gserviceaccount.com"
client_id = "100290504332764846323"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/terasaka-demo%40terasaka-demo.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
